version: '3.3'
services:
  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    command: yarn serve
    volumes:
      - ./client/app:/app
    ports:
      - "8081:8080"
    depends_on:
      - server

  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server/app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
    environment:
      DEBUG: 'True'
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres'

  db:
    image: postgres:12.4-alpine
    env_file: .env
