# Generated by Django 3.1.2 on 2021-05-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20210521_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='tags',
            field=models.ManyToManyField(blank=True, to='budget.ExpenseTag'),
        ),
        migrations.AlterField(
            model_name='income',
            name='tags',
            field=models.ManyToManyField(blank=True, to='budget.IncomeTag'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='budget.TransferTag'),
        ),
    ]
