# Generated by Django 3.1.2 on 2021-06-05 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_auto_20210605_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.budget'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='budget_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer_from', to='budget.budget'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='budget_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer_to', to='budget.budget'),
        ),
    ]
