# Generated by Django 3.1.2 on 2021-06-11 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_auto_20210605_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budget'),
        ),
        migrations.AlterField(
            model_name='income',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budget'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='budget_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='budget.budget'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='budget_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='budget.budget'),
        ),
    ]
